// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceStay.Infra.Data;

#nullable disable

namespace SpaceStay.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SpaceStay.Core.Domain.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int")
                        .HasColumnName("resolved_by");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("enum('info','warning','critical')")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('open','acknowledged','resolved')")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("SensorId");

                    b.HasIndex("Status");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime")
                        .HasColumnName("check_in");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime")
                        .HasColumnName("check_out");

                    b.Property<int>("GuestId")
                        .HasColumnType("int")
                        .HasColumnName("guest_id");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('confirmed','active','completed')")
                        .HasDefaultValue("confirmed")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("ModuleId", "Status");

                    b.ToTable("bookings", t =>
                        {
                            t.HasCheckConstraint("chk_bookings_dates", "check_out > check_in");
                        });
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Excursion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id");

                    b.ToTable("excursions", t =>
                        {
                            t.HasCheckConstraint("chk_excursions_capacity", "capacity > 0");
                        });
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.ExcursionBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExcursionId")
                        .HasColumnType("int")
                        .HasColumnName("excursion_id");

                    b.Property<int>("GuestId")
                        .HasColumnType("int")
                        .HasColumnName("guest_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('booked','cancelled','attended')")
                        .HasDefaultValue("booked")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExcursionId");

                    b.HasIndex("GuestId", "ExcursionId")
                        .IsUnique();

                    b.ToTable("excursion_bookings");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("email");

                    b.Property<bool>("MedicalClearance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("medical_clearance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nationality");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("guests");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('available','occupied','maintenance')")
                        .HasDefaultValue("available")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('suite','common','lab')")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("modules", t =>
                        {
                            t.HasCheckConstraint("chk_modules_capacity", "capacity > 0");
                        });
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxSafe")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("max_safe");

                    b.Property<decimal>("MinSafe")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("min_safe");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('o2','co2','pressure','temperature','humidity','water')")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Type")
                        .IsUnique();

                    b.ToTable("sensors", t =>
                        {
                            t.HasCheckConstraint("chk_sensors_range", "max_safe > min_safe");
                        });
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "RecordedAt");

                    b.ToTable("sensor_readings");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("enum('admin','engineer','concierge')")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("staff");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Alert", b =>
                {
                    b.HasOne("SpaceStay.Core.Domain.Module", "Module")
                        .WithMany("Alerts")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceStay.Core.Domain.Staff", "ResolvedByStaff")
                        .WithMany("ResolvedAlerts")
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SpaceStay.Core.Domain.Sensor", "Sensor")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("ResolvedByStaff");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Booking", b =>
                {
                    b.HasOne("SpaceStay.Core.Domain.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceStay.Core.Domain.Module", "Module")
                        .WithMany("Bookings")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.ExcursionBooking", b =>
                {
                    b.HasOne("SpaceStay.Core.Domain.Excursion", "Excursion")
                        .WithMany("ExcursionBookings")
                        .HasForeignKey("ExcursionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceStay.Core.Domain.Guest", "Guest")
                        .WithMany("ExcursionBookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excursion");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Sensor", b =>
                {
                    b.HasOne("SpaceStay.Core.Domain.Module", "Module")
                        .WithMany("Sensors")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.SensorReading", b =>
                {
                    b.HasOne("SpaceStay.Core.Domain.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Excursion", b =>
                {
                    b.Navigation("ExcursionBookings");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Guest", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ExcursionBookings");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Module", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Bookings");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Sensor", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("SpaceStay.Core.Domain.Staff", b =>
                {
                    b.Navigation("ResolvedAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
